rewrite ^/about-vb-engineering.html$ /about/ permanent;
rewrite ^/about-us.html$ /about/ permanent;
rewrite ^/Contact$ /contact/ permanent;
rewrite ^/Contact.html$ /contact/ permanent;
rewrite ^/Contactus$ /contact/ permanent;
rewrite ^/Contacts.html$ /contact/ permanent;
rewrite ^/Contactus.html$ /contact/ permanent;
rewrite ^/Enquiry$ /contact/ permanent;
rewrite ^/service-request$ /contact/ permanent;
rewrite ^/usa-electrical-Arc-Flash-study-services.html$ /locations/usa/risk-safety-amc/ permanent;
rewrite ^/arc-flash-study-UAE.html$ /locations/uae/risk-safety-amc/ permanent;
rewrite ^/arc-flash-Study-Consultant-UAE.html$ /locations/uae/risk-safety-amc/ permanent;
rewrite ^/arc-flash-study-Qatar.html$ /locations/qatar/risk-safety-amc/ permanent;
rewrite ^/qatar-electrical-Arc-Flash-study-services.html$ /locations/qatar/risk-safety-amc/ permanent;
rewrite ^/arc-flash-study-saudi-arabia.html$ /locations/saudi-arabia/risk-safety-amc/ permanent;
rewrite ^/kingdom-of-saudi-arabia-arc-flash-study.html$ /ksa-arc-flash-study.html permanent;
rewrite ^/kingdom-of-saudi-arabia-electrical-Arc-Flash-study-services.html$ /locations/saudi-arabia/risk-safety-amc/ permanent;
rewrite ^/arc-flash-australia.html$ /locations/australia/risk-safety-amc/ permanent;
rewrite ^/australia-electrical-Arc-Flash-study-services.html$ /locations/australia/risk-safety-amc/ permanent;
rewrite ^/indonesia-electrical-Arc-Flash-study-services.html$ /locations/indonesia/risk-safety-amc/ permanent;
rewrite ^/arc-flash-risk-assessment-china$ /locations/china/risk-safety-amc/ permanent;
rewrite ^/arc-flash-analysis-india.html$ /locations/india/risk-safety-amc/ permanent;
rewrite ^/arc-flash-risk-assessment-india.html$ /locations/india/risk-safety-amc/ permanent;
rewrite ^/arc-flash-ppe-india.html$ /locations/india/risk-safety-amc/ permanent;
rewrite ^/power-system-studies.html$ /services/ permanent;
rewrite ^/load-flow-analysis-for-oil-and-gas-rigs.html$ /services/ permanent;
rewrite ^/short-circuit-analysis.html$ /services/ permanent;
rewrite ^/short-circuit-studies.html$ /services/ permanent;
rewrite ^/short-circuit-studies-for-oil-and-gas-rigs.html$ /services/ permanent;
rewrite ^/relay-coordination.html$ /services/ permanent;
rewrite ^/relay-coordination-india.html$ /services/ permanent;
rewrite ^/relay-coordination-study.html$ /services/ permanent;
rewrite ^/harmonic-analysis.html$ /services/ permanent;
rewrite ^/harmonic-analysis-india.html$ /services/ permanent;
rewrite ^/arc-flash-risk-assessment.html$ /services/ permanent;
rewrite ^/arc-flash-risk-assessment-for-oil-rigs.html$ /services/ permanent;
rewrite ^/dc-short-circuit-studies.html$ /services/ permanent;
rewrite ^/dc-arc-flash-studies.html$ /services/ permanent;
rewrite ^/transient-stability-studies.html$ /services/ permanent;
rewrite ^/transient-stability-and-load-shedding-studies.html$ /services/ permanent;
rewrite ^/voltage-drop-studies.html$ /services/ permanent;
rewrite ^/motor-starting-studies.html$ /services/ permanent;
rewrite ^/insulation-coordination-studies.html$ /services/ permanent;
rewrite ^/risk-assessments-consultancy.html$ /services/ permanent;
rewrite ^/industrial-risk-assessments.html$ /services/ permanent;
rewrite ^/safety-audits.html$ /services/ permanent;
rewrite ^/osha-process-safety-hazop-study.html$ /services/ permanent;
rewrite ^/e-hazop-study.html$ /services/ permanent;
rewrite ^/engineering-services.html$ /services/ permanent;
rewrite ^/electrical-engineering-services.html$ /services/ permanent;
rewrite ^/services.html$ /services/ permanent;
rewrite ^/cad-drafting-services.html$ /services/ permanent;
rewrite ^/3d-cad-drafting-services.html$ /services/ permanent;
rewrite ^/cad-drawing-preparation.html$ /services/ permanent;
rewrite ^/PandID-Drawings-Preperation-India.html$ /services/ permanent;
rewrite ^/vb-sitemap.html$ /sitemap.xml permanent;rewrite ^/services/simulation-evaluation/throughput-optimisation/$ /services/simulation-evaluation/ permanent;
